/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dum.h"

float *
average_1_svc(X_array *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Average function called...\n");
	
	int sum=0;
	int i;

	for(i=0;i<argp->X_size;i++)
		sum+=argp->X.X_val[i];
		
	result=sum/argp->X_size;
	
	return &result;
}

max_min *
maxmin_1_svc(X_array *argp, struct svc_req *rqstp)
{
	static max_min  result;

	printf("Max/Min function called...\n");

	int i;

	result.max=-999999;
	result.min=999999;
	
	for(i=0;i<argp->X_size;i++)
		if(argp->X.X_val[i]>result.max)
			result.max=argp->X.X_val[i];
			
	for(i=0;i<argp->X_size;i++)
		if(argp->X.X_val[i]<result.min)
			result.min=argp->X.X_val[i];

	return &result;
}

rX *
product_1_svc(r_times_X *argp, struct svc_req *rqstp)
{
	static rX  result;

	printf("r*X[] function called...\n");

	result.prod.prod_len=argp->X_size;
	result.prod.prod_val=(float *)malloc(argp->X_size*sizeof(float));
	
	int i;
	
	for(i=0;i<argp->X_size;i++)
		result.prod.prod_val[i]=argp->r*argp->X.X_val[i];

	return &result;
}
