/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dum.h"

bool_t
xdr_X_array (XDR *xdrs, X_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->X_size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_min (XDR *xdrs, max_min *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_r_times_X (XDR *xdrs, r_times_X *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->X_size))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rX (XDR *xdrs, rX *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->prod.prod_val, (u_int *) &objp->prod.prod_len, 100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
