/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dum.h"


void
dum_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	X_array  average_1_arg;
	max_min  *result_2;
	X_array  maxmin_1_arg;
	rX  *result_3;
	r_times_X  product_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DUM_PROG, DUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int flag=1;
	int choice;
	int i;
	int n;
	float r;

	do
	{
		printf("==========================\n");
		printf("=====Dummy Operations=====\n");
		printf("==========================\n");
		printf("1. average of X[]\n");
		printf("2. max and min of X[]\n");
		printf("3. r*X[]\n");
		printf("4. Quit\n");
		printf("==========================\n");
		printf("Choice: ");
		scanf("%d", &choice);
		printf("==========================\n");
		
		if(choice==1)
		{
			///////////////////////////////////////////////////////
			//average of X[]
			///////////////////////////////////////////////////////
			printf("Give size of X[]: ");
			scanf("%d", &n);
		
			average_1_arg.X.X_len=n;
			average_1_arg.X_size=n;
			average_1_arg.X.X_val=(int *) malloc(n*sizeof(int));
		
			printf("\n");
		
			for(i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &average_1_arg.X.X_val[i]);	
			}
	
			result_1 = average_1(&average_1_arg, clnt);
			
			if (result_1 == (float *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("\n");
				printf("Average of X[] == %.2f\n", *result_1);
				printf("\n");
			}
			///////////////////////////////////////////////////////
			///////////////////////////////////////////////////////
		}
		else if(choice==2)
		{
			///////////////////////////////////////////////////////
			//max and min of X[]
			///////////////////////////////////////////////////////
			printf("Give size of X[]: ");
			scanf("%d", &n);
		
			maxmin_1_arg.X.X_len=n;
			maxmin_1_arg.X_size=n;
			maxmin_1_arg.X.X_val=(int *) malloc(n*sizeof(int));
			
			printf("\n");
			
			for(i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &maxmin_1_arg.X.X_val[i]);	
			}
	
			result_2 = maxmin_1(&maxmin_1_arg, clnt);
			
			if (result_2 == (max_min *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("\n");
				printf("Max of X[] == %d\n", result_2->max);
				printf("Min of X[] == %d\n", result_2->min);
				printf("\n");
			}	
			///////////////////////////////////////////////////////
			///////////////////////////////////////////////////////
		}		
		else if(choice==3)
		{
			///////////////////////////////////////////////////////
			//r*X[]
			///////////////////////////////////////////////////////
			printf("Give size of X[]: ");
			scanf("%d", &n);
		
			printf("\n");
			
			product_1_arg.X.X_len=n;
			product_1_arg.X_size=n;
			product_1_arg.X.X_val=(int *) malloc(n*sizeof(int));
			
			for(i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &product_1_arg.X.X_val[i]);	
			}
			
			printf("Give floating number r: ");
			scanf("%f", &r);
			
			product_1_arg.r=r;
			
			printf("\n");
			
			result_3 = product_1(&product_1_arg, clnt);
			
			if (result_3 == (rX *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("\n");
				for(i=0;i<n;i++)
					printf("r*X[%d] == %.2f\n", i, result_3->prod.prod_val[i]);
				printf("\n");
			}
			///////////////////////////////////////////////////////
			///////////////////////////////////////////////////////
		}
		else if(choice==4)
		{
			flag=0;
		}
		else
		{
			printf("Invalid Choice. Try Again.\n\n");
		}
	}while(flag);	

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dum_prog_1 (host);
exit (0);
}
