/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dum.h"


void dum_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	X_arr  average_1_arg;
	max_min  *result_2;
	X_arr  max_and_min_1_arg;
	prod  *result_3;
	X_times_r  product_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DUM_PROG, DUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = average_1(&average_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = max_and_min_1(&max_and_min_1_arg, clnt);
	if (result_2 == (max_min *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = product_1(&product_1_arg, clnt);
	if (result_3 == (prod *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	int i;
	int flag=1;
	int n;
	int r;
	
	int choice;

	printf("--------------------------------------------------------------------------\n");

	do
	{
		
		printf("==========================\n");
		printf("=====Dummy Operations=====\n");
		printf("==========================\n");
		printf("1. average of X[] \n");
		printf("2. max & min of X[] \n");
		printf("3. r*X[] \n");
		printf("4. Exit \n");
		printf("==========================\n");
		printf("Choice: ");
		scanf("%d", &choice);
		printf("==========================\n");
		
		
	
	
		if(choice==1)
		{
			///////////////////////////////////////
			//average of X[]
			///////////////////////////////////////
			printf("Number of elements: ");
			scanf("%d", &n);
			
			average_1_arg.X.X_len=n;
			average_1_arg.X_size=n;
			average_1_arg.X.X_val=(int *)malloc(n*sizeof(int));
			
			for(i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &average_1_arg.X.X_val[i]);
			}
				
			result_1=average_1(&average_1_arg, clnt);
			
			printf("Average of X[]: %.2f\n", *result_1);
			///////////////////////////////////////
			///////////////////////////////////////
		}
		else if(choice==2)
		{
			///////////////////////////////////////
			//max and min of X[]
			///////////////////////////////////////
			printf("Number of elements: ");
			scanf("%d", &n);

			max_and_min_1_arg.X.X_len=n;
			max_and_min_1_arg.X_size=n;
			max_and_min_1_arg.X.X_val=(int *)malloc(n*sizeof(int));
			
			for(i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &max_and_min_1_arg.X.X_val[i]);
			}
				
			result_2=max_and_min_1(&max_and_min_1_arg, clnt);
			
			printf("Max of X[]: %d\n", result_2->max);
			printf("Min of X[]: %d\n", result_2->min);
			///////////////////////////////////////
			///////////////////////////////////////
		}
		else if(choice==3)
		{
			///////////////////////////////////////
			//r*X[]
			///////////////////////////////////////
			printf("Number of elements: ");
			scanf("%d", &n);
			
			printf("r: ");
			scanf("%d", &r);
			
			product_1_arg.X.X_len=n;
			product_1_arg.X_size=n;
			product_1_arg.r=r;
			product_1_arg.X.X_val=(int *)malloc(n*sizeof(int));
			
			for(i=0;i<n;i++)
			{
				printf("X[%d] = ", i);
				scanf("%d", &product_1_arg.X.X_val[i]);
			}
				
			result_3=product_1(&product_1_arg, clnt);
			
			for(i=0;i<n;i++)
				printf("%.2f*X[%d]=%.2f\n", product_1_arg.r, i, result_3->prod.prod_val[i]);
			///////////////////////////////////////
			///////////////////////////////////////
		}
		else if(choice==4)
		{
			flag=0;
		}
		else
		{
			printf("Invalid Choice. Terminating in 3...2...1...\n");
			exit(1);
		}
	}while(flag);
	
	printf("--------------------------------------------------------------------------\n");
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	dum_prog_1 (host);
exit (0);
}
